<?php

declare(strict_types=1);

use Modules\Auth\AuthController;
use Modules\Billing\BillingController;
use Modules\Clients\ClientController;
use Modules\ClientPortal\ClientPortalController;
use Modules\Consultants\ConsultantController;
use Modules\Dashboard\DashboardController;
use Modules\Documents\DocumentController;
use Modules\Reminders\ReminderController;
use Modules\Reports\ReportController;
use Modules\Search\SearchController;
use Modules\ServiceOrders\ServiceOrderController;
use Modules\Users\UserController;
use Modules\Workflow\WorkflowController;
use Modules\Attendance\AttendanceController;
use Modules\DSC\DSCController;
use Modules\Workforce\WorkforceController;
use Modules\Accounts\AccountsController;
use Modules\Settings\SettingsController;

$router->get('/', [AuthController::class, 'showLanding'], ['guest']);
$router->get('/login', [AuthController::class, 'showLogin'], ['guest']);
$router->post('/login', [AuthController::class, 'login'], ['guest']);
$router->get('/forgot-password', [AuthController::class, 'showForgotPassword'], ['guest']);
$router->post('/forgot-password', [AuthController::class, 'forgotPassword'], ['guest']);
$router->get('/reset-password', [AuthController::class, 'showResetPassword'], ['guest']);
$router->post('/reset-password', [AuthController::class, 'resetPassword'], ['guest']);
$router->get('/register-client', [ClientController::class, 'publicCreate'], ['guest']);
$router->post('/register-client', [ClientController::class, 'publicStore'], ['guest']);
$router->get('/change-password', [AuthController::class, 'showChangePassword'], ['auth']);
$router->post('/change-password', [AuthController::class, 'changePassword'], ['auth']);
$router->get('/logout', function () { redirect('/'); });
$router->post('/logout', [AuthController::class, 'logout'], ['auth']);
$router->get('/dashboard', [DashboardController::class, 'index'], ['auth']);
$router->get('/search', [SearchController::class, 'index'], ['auth', 'permission:search.view']);
$router->get('/search/quick', [SearchController::class, 'quick'], ['auth', 'permission:search.quick,search.view']);
$router->get('/search/advanced', [SearchController::class, 'advanced'], ['auth', 'permission:search.advanced']);
$router->get('/search/history', [SearchController::class, 'history'], ['auth', 'permission:search.history,search.audit']);
$router->get('/documents/show', [DocumentController::class, 'show'], ['auth', 'permission:documents.view,documents.download,portal.self_access']);
$router->get('/documents/{id}/download', [DocumentController::class, 'download'], ['auth', 'permission:documents.download,portal.self_access']);
$router->get('/documents/{id}/preview', [DocumentController::class, 'preview'], ['auth', 'permission:documents.view,documents.download,portal.self_access']);
$router->post('/documents/replace', [DocumentController::class, 'replace'], ['auth', 'permission:documents.replace']);
$router->post('/documents/verify', [DocumentController::class, 'verify'], ['auth', 'permission:documents.verify']);
$router->get('/documents', [DocumentController::class, 'index'], ['auth', 'permission:documents.view,documents.download']);
$router->get('/documents/requests', [DocumentController::class, 'requests'], ['auth', 'permission:documents.request']);
$router->get('/documents/requests/create', [DocumentController::class, 'requestForm'], ['auth', 'permission:documents.request']);
$router->post('/documents/requests', [DocumentController::class, 'createRequest'], ['auth', 'permission:documents.request']);
$router->post('/documents/requests/mark-received', [DocumentController::class, 'markReceived'], ['auth', 'permission:documents.upload']);
$router->post('/documents/requests/cancel', [DocumentController::class, 'cancelRequest'], ['auth', 'permission:documents.request']);
$router->get('/documents/movement', [DocumentController::class, 'movement'], ['auth', 'permission:documents.movement.view']);
$router->get('/documents/movement/create', [DocumentController::class, 'movementForm'], ['auth', 'permission:documents.movement.manage']);
$router->post('/documents/movement', [DocumentController::class, 'createMovement'], ['auth', 'permission:documents.movement.manage']);
$router->post('/documents/movement/return', [DocumentController::class, 'returnMovement'], ['auth', 'permission:documents.movement.manage']);
$router->post('/documents/movement/archive', [DocumentController::class, 'archiveMovement'], ['auth', 'permission:documents.movement.manage']);
$router->get('/dsc', [DSCController::class, 'index'], ['auth', 'permission:dsc.view']);
$router->get('/dsc/create', [DSCController::class, 'create'], ['auth', 'permission:dsc.create']);
$router->post('/dsc', [DSCController::class, 'store'], ['auth', 'permission:dsc.create']);
$router->get('/dsc/show', [DSCController::class, 'show'], ['auth', 'permission:dsc.view']);
$router->get('/dsc/edit', [DSCController::class, 'edit'], ['auth', 'permission:dsc.edit']);
$router->post('/dsc/update', [DSCController::class, 'update'], ['auth', 'permission:dsc.edit']);
$router->post('/dsc/archive', [DSCController::class, 'archive'], ['auth', 'permission:dsc.edit']);
$router->get('/dsc/movement', [DSCController::class, 'movement'], ['auth', 'permission:dsc.movement.view']);
$router->get('/dsc/movement/create', [DSCController::class, 'movementForm'], ['auth', 'permission:dsc.movement.manage']);
$router->post('/dsc/movement', [DSCController::class, 'createMovement'], ['auth', 'permission:dsc.movement.manage']);
$router->post('/dsc/movement/return', [DSCController::class, 'returnMovement'], ['auth', 'permission:dsc.movement.manage']);
$router->post('/dsc/movement/archive', [DSCController::class, 'archiveMovement'], ['auth', 'permission:dsc.movement.manage']);
$router->get('/dsc/usage', [DSCController::class, 'usage'], ['auth', 'permission:dsc.usage.view']);
$router->get('/dsc/usage/create', [DSCController::class, 'usageForm'], ['auth', 'permission:dsc.usage.log']);
$router->post('/dsc/usage', [DSCController::class, 'createUsage'], ['auth', 'permission:dsc.usage.log']);
$router->get('/dsc/renewals', [DSCController::class, 'renewals'], ['auth', 'permission:dsc.renewal.view']);
$router->post('/dsc/renewals/update', [DSCController::class, 'updateRenewal'], ['auth', 'permission:dsc.renewal.manage']);
$router->get('/dsc/reports', [DSCController::class, 'reports'], ['auth', 'permission:dsc.reports.view']);
$router->get('/reports', [ReportController::class, 'index'], ['auth', 'permission:reports.view,reports.financial']);
$router->get('/reports/document-access', [ReportController::class, 'documentAccess'], ['auth', 'permission:documents.report,documents.access_log.view']);
$router->get('/reminders', [ReminderController::class, 'index'], ['auth', 'permission:reminders.view']);
$router->get('/reminders/templates', [ReminderController::class, 'templates'], ['auth', 'permission:reminders.view']);
$router->get('/reminders/templates/form', [ReminderController::class, 'templateForm'], ['auth', 'permission:reminders.create,reminders.edit']);
$router->post('/reminders/templates/save', [ReminderController::class, 'saveTemplate'], ['auth', 'permission:reminders.create,reminders.edit']);
$router->get('/reminders/escalations', [ReminderController::class, 'escalations'], ['auth', 'permission:reminders.view']);
$router->get('/reminders/escalations/form', [ReminderController::class, 'escalationForm'], ['auth', 'permission:reminders.create,reminders.edit']);
$router->post('/reminders/escalations/save', [ReminderController::class, 'saveEscalation'], ['auth', 'permission:reminders.create,reminders.edit']);
$router->get('/reminders/register', [ReminderController::class, 'register'], ['auth', 'permission:reminders.report']);
$router->get('/reminders/pending', [ReminderController::class, 'pending'], ['auth', 'permission:reminders.report']);
$router->get('/reminders/effectiveness', [ReminderController::class, 'effectiveness'], ['auth', 'permission:reminders.report']);
$router->get('/reminders/escalation-report', [ReminderController::class, 'escalationReport'], ['auth', 'permission:reminders.report']);
$router->post('/reminders/run-scheduler', [ReminderController::class, 'runScheduler'], ['auth', 'permission:reminders.send']);
$router->get('/reports/clients', [ReportController::class, 'clients'], ['auth', 'permission:reports.view']);
$router->get('/reports/service-orders', [ReportController::class, 'serviceOrders'], ['auth', 'permission:reports.view']);
$router->get('/reports/pso', [ReportController::class, 'pso'], ['auth', 'permission:reports.view']);
$router->get('/reports/invoices', [ReportController::class, 'invoices'], ['auth', 'permission:reports.financial']);
$router->get('/reports/receipts', [ReportController::class, 'receipts'], ['auth', 'permission:reports.financial']);
$router->get('/reports/outstanding', [ReportController::class, 'outstanding'], ['auth', 'permission:reports.financial']);
$router->get('/reports/gst-summary', [ReportController::class, 'gstSummary'], ['auth', 'permission:reports.view']);
$router->get('/reports/revenue', [ReportController::class, 'revenue'], ['auth', 'permission:reports.financial']);
$router->get('/reports/consultants', [ReportController::class, 'consultants'], ['auth', 'permission:reports.view']);
$router->get('/reports/operational', [ReportController::class, 'operational'], ['auth', 'permission:reports.view']);
$router->get('/reports/workforce', [ReportController::class, 'workforce'], ['auth', 'permission:reports.view']);
$router->get('/reports/attendance', [ReportController::class, 'attendance'], ['auth', 'permission:reports.view']);
$router->get('/reports/documents', [ReportController::class, 'documents'], ['auth', 'permission:reports.view']);
$router->get('/reports/dsc', [ReportController::class, 'dsc'], ['auth', 'permission:reports.view']);
$router->get('/reports/accounts', [ReportController::class, 'accounts'], ['auth', 'permission:reports.view']);
$router->get('/reports/audit', [ReportController::class, 'audit'], ['auth', 'permission:reports.view']);
$router->get('/users', [UserController::class, 'index'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->get('/users/create', [UserController::class, 'create'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->post('/users', [UserController::class, 'store'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->get('/users/show', [UserController::class, 'show'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->get('/users/edit', [UserController::class, 'edit'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->post('/users/update', [UserController::class, 'update'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->get('/users/rights', [UserController::class, 'rights'], ['auth', 'permission:users.manage.rights,users.manage.internal']);
$router->post('/users/rights', [UserController::class, 'saveRights'], ['auth', 'permission:users.manage.rights,users.manage.internal']);
$router->post('/users/archive', [UserController::class, 'archive'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->post('/users/activate', [UserController::class, 'activate'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->post('/users/reset-password', [UserController::class, 'resetPassword'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->get('/clients', [ClientController::class, 'index'], ['auth', 'permission:clients.view']);
$router->get('/clients/create', [ClientController::class, 'create'], ['auth', 'permission:clients.create']);
$router->post('/clients', [ClientController::class, 'store'], ['auth', 'permission:clients.create']);
$router->get('/clients/show', [ClientController::class, 'show'], ['auth', 'permission:clients.view']);
$router->get('/clients/credentials', [ClientController::class, 'credentials'], ['auth', 'permission:clients.view']);
$router->get('/clients/edit', [ClientController::class, 'edit'], ['auth', 'permission:clients.edit']);
$router->post('/clients/credentials', [ClientController::class, 'saveCredentials'], ['auth', 'permission:clients.credentials.manage']);
$router->post('/clients/update', [ClientController::class, 'update'], ['auth', 'permission:clients.edit']);
$router->post('/clients/archive', [ClientController::class, 'archive'], ['auth', 'permission:clients.archive']);
$router->get('/client-portal/pso', [ClientPortalController::class, 'index'], ['auth', 'permission:portal.self_access']);
$router->get('/client-portal/account', [ClientPortalController::class, 'account'], ['auth', 'permission:portal.self_access']);
$router->get('/client-portal/documents', [ClientPortalController::class, 'documents'], ['auth', 'permission:portal.self_access']);
$router->get('/client-portal/support', [ClientPortalController::class, 'support'], ['auth', 'permission:portal.self_access']);
$router->get('/client-portal/pso/create', [ClientPortalController::class, 'create'], ['auth', 'permission:portal.pso.create']);
$router->post('/client-portal/pso', [ClientPortalController::class, 'store'], ['auth', 'permission:portal.pso.create']);
$router->get('/client-portal/pso/show', [ClientPortalController::class, 'show'], ['auth', 'permission:portal.self_access']);
$router->post('/client-portal/payments', [ClientPortalController::class, 'payInvoice'], ['auth', 'permission:portal.self_access']);
$router->post('/client-portal/pso/recommend', [ClientPortalController::class, 'recommendApproval'], ['auth', 'permission:portal.pso.review']);
$router->post('/client-portal/pso/approve', [ClientPortalController::class, 'approve'], ['auth', 'permission:portal.pso.approve']);
$router->post('/client-portal/pso/reject', [ClientPortalController::class, 'reject'], ['auth', 'permission:portal.pso.reject']);
$router->get('/billing', [BillingController::class, 'index'], ['auth', 'permission:billing.view']);
$router->get('/billing/show', [BillingController::class, 'show'], ['auth', 'permission:billing.view']);
$router->get('/billing/invoice', [BillingController::class, 'invoice'], ['auth', 'permission:billing.view,portal.self_access']);
$router->get('/billing/receipt', [BillingController::class, 'receipt'], ['auth', 'permission:billing.view,portal.self_access']);
$router->post('/billing/disbursements', [BillingController::class, 'addDisbursement'], ['auth', 'permission:billing.disbursements.manage']);
$router->post('/billing/invoices', [BillingController::class, 'createInvoice'], ['auth', 'permission:billing.invoices.manage']);
$router->post('/billing/payments', [BillingController::class, 'recordPayment'], ['auth', 'permission:billing.payments.manage']);
$router->get('/consultants', [ConsultantController::class, 'index'], ['auth', 'permission:consultants.view']);
$router->get('/consultants/show', [ConsultantController::class, 'show'], ['auth', 'permission:consultants.view,consultants.bills.review,consultants.payments.record']);
$router->post('/consultants/assign', [ConsultantController::class, 'assign'], ['auth', 'permission:consultants.assign']);
$router->post('/consultants/deliverables', [ConsultantController::class, 'uploadDeliverable'], ['auth', 'permission:consultants.deliverables.upload']);
$router->post('/consultants/deliverables/review', [ConsultantController::class, 'reviewDeliverable'], ['auth', 'permission:consultants.deliverables.review']);
$router->post('/consultants/bills', [ConsultantController::class, 'createBill'], ['auth', 'permission:consultants.bills.create']);
$router->post('/consultants/bills/review', [ConsultantController::class, 'reviewBill'], ['auth', 'permission:consultants.bills.review']);
$router->post('/consultants/payments', [ConsultantController::class, 'recordPayment'], ['auth', 'permission:consultants.payments.record']);
$router->get('/service-orders', [ServiceOrderController::class, 'index'], ['auth', 'permission:service_orders.view']);
$router->get('/service-orders/create', [ServiceOrderController::class, 'create'], ['auth', 'permission:service_orders.create']);
$router->post('/service-orders', [ServiceOrderController::class, 'store'], ['auth', 'permission:service_orders.create']);
$router->get('/service-orders/show', [ServiceOrderController::class, 'show'], ['auth', 'permission:service_orders.view']);
$router->post('/service-orders/documents', [ServiceOrderController::class, 'uploadDocument'], ['auth', 'permission:service_orders.create,workflow.advance']);
$router->post('/workflow/advance', [WorkflowController::class, 'advance'], ['auth', 'permission:workflow.advance']);
$router->post('/workflow/payment', [WorkflowController::class, 'recordPayment'], ['auth', 'permission:workflow.payment.record']);
$router->post('/workflow/acknowledgement', [WorkflowController::class, 'captureAcknowledgement'], ['auth', 'permission:workflow.acknowledgement.capture']);
$router->post('/workflow/e-verification-done', [WorkflowController::class, 'markEVerificationDone'], ['auth', 'permission:workflow.everification.complete']);
$router->post('/workflow/close-procedural', [WorkflowController::class, 'completeProceduralClosure'], ['auth', 'permission:workflow.close.procedural']);
$router->post('/workflow/close-accounting', [WorkflowController::class, 'completeAccountingClosure'], ['auth', 'permission:workflow.close.accounting']);
$router->post('/workflow/close-final', [WorkflowController::class, 'completeFinalClosure'], ['auth', 'permission:workflow.close.final']);
$router->post('/workflow/reopen', [WorkflowController::class, 'reopenMilestone'], ['auth', 'permission:workflow.reopen']);
$router->post('/workflow/milestone-update', [WorkflowController::class, 'updateMilestone'], ['auth', 'permission:workflow.advance,workflow.payment.record,workflow.acknowledgement.capture,workflow.everification.complete']);
$router->post('/workflow/follow-up', [WorkflowController::class, 'logFollowUp'], ['auth', 'permission:workflow.followup.log']);

$router->get('/attendance', [AttendanceController::class, 'index'], ['auth', 'permission:attendance.view']);
$router->get('/attendance/today', [AttendanceController::class, 'today'], ['auth', 'permission:attendance.view']);
$router->get('/attendance/activity/start', [AttendanceController::class, 'showActivityForm'], ['auth', 'permission:attendance.activity.manage']);
$router->post('/attendance/activity/start', [AttendanceController::class, 'startActivity'], ['auth', 'permission:attendance.activity.manage']);
$router->post('/attendance/activity/stop', [AttendanceController::class, 'stopActivity'], ['auth', 'permission:attendance.activity.manage']);
$router->post('/attendance/activity/pause', [AttendanceController::class, 'pauseActivity'], ['auth', 'permission:attendance.activity.manage']);
$router->post('/attendance/activity/resume', [AttendanceController::class, 'resumeActivity'], ['auth', 'permission:attendance.activity.manage']);
$router->get('/attendance/report', [AttendanceController::class, 'showReportForm'], ['auth', 'permission:attendance.report.submit']);
$router->post('/attendance/report', [AttendanceController::class, 'submitReport'], ['auth', 'permission:attendance.report.submit']);
$router->get('/attendance/admin', [AttendanceController::class, 'adminReports'], ['auth', 'permission:attendance.report.review']);
$router->get('/attendance/report/show', [AttendanceController::class, 'showReport'], ['auth', 'permission:attendance.view']);
$router->post('/attendance/report/review', [AttendanceController::class, 'reviewReport'], ['auth', 'permission:attendance.report.review']);
$router->get('/attendance/productivity', [AttendanceController::class, 'productivity'], ['auth', 'permission:attendance.productivity.view']);
$router->post('/attendance/emergency-logout', [AttendanceController::class, 'emergencyLogout'], ['auth', 'permission:attendance.view']);
$router->get('/workforce', [WorkforceController::class, 'index'], ['auth', 'permission:workforce.view']);
$router->get('/workforce/consultants', [WorkforceController::class, 'consultants'], ['auth', 'permission:workforce.consultants.view']);
$router->get('/workforce/consultants/create', [WorkforceController::class, 'consultantForm'], ['auth', 'permission:workforce.consultants.manage']);
$router->post('/workforce/consultants', [WorkforceController::class, 'storeConsultant'], ['auth', 'permission:workforce.consultants.manage']);
$router->get('/workforce/consultants/show', [WorkforceController::class, 'showConsultant'], ['auth', 'permission:workforce.consultants.view']);
$router->get('/workforce/consultants/edit', [WorkforceController::class, 'editConsultant'], ['auth', 'permission:workforce.consultants.manage']);
$router->post('/workforce/consultants/update', [WorkforceController::class, 'updateConsultant'], ['auth', 'permission:workforce.consultants.manage']);
$router->post('/workforce/consultants/archive', [WorkforceController::class, 'archiveConsultant'], ['auth', 'permission:workforce.consultants.manage']);
$router->get('/workforce/consultant-assignments', [WorkforceController::class, 'consultantAssignments'], ['auth', 'permission:workforce.consultants.view']);
$router->get('/workforce/consultant-assignments/create', [WorkforceController::class, 'consultantAssignmentForm'], ['auth', 'permission:workforce.consultants.manage']);
$router->post('/workforce/consultant-assignments', [WorkforceController::class, 'createAssignment'], ['auth', 'permission:workforce.consultants.manage']);
$router->post('/workforce/consultant-assignments/status', [WorkforceController::class, 'updateAssignmentStatus'], ['auth', 'permission:workforce.consultants.manage']);
$router->get('/workforce/consultant-deliverables', [WorkforceController::class, 'consultantDeliverables'], ['auth', 'permission:workforce.consultants.view']);
$router->post('/workforce/consultant-deliverables/status', [WorkforceController::class, 'updateDeliverableStatus'], ['auth', 'permission:workforce.consultants.manage']);
$router->get('/workforce/consultant-bills', [WorkforceController::class, 'consultantBills'], ['auth', 'permission:workforce.consultants.view']);
$router->post('/workforce/consultant-bills/status', [WorkforceController::class, 'updateBillStatus'], ['auth', 'permission:workforce.consultants.manage']);
$router->get('/workforce/consultant-payments', [WorkforceController::class, 'consultantPayments'], ['auth', 'permission:workforce.consultants.view']);
$router->post('/workforce/consultant-payments', [WorkforceController::class, 'createPayment'], ['auth', 'permission:workforce.consultants.manage']);
$router->get('/accounts', [AccountsController::class, 'index'], ['auth', 'permission:accounts.view,billing.view']);
$router->get('/accounts/invoices', [AccountsController::class, 'invoices'], ['auth', 'permission:accounts.view,billing.view']);
$router->get('/accounts/receipts', [AccountsController::class, 'receipts'], ['auth', 'permission:accounts.view,billing.view']);
$router->get('/accounts/payments', [AccountsController::class, 'payments'], ['auth', 'permission:accounts.view,billing.view']);
$router->get('/accounts/outstanding', [AccountsController::class, 'outstanding'], ['auth', 'permission:accounts.view,billing.view']);
$router->get('/accounts/ageing', [AccountsController::class, 'ageing'], ['auth', 'permission:accounts.view,billing.view']);
$router->get('/accounts/followups', [AccountsController::class, 'followups'], ['auth', 'permission:accounts.view,billing.view']);
$router->post('/accounts/followups', [AccountsController::class, 'createFollowup'], ['auth', 'permission:accounts.view,billing.view']);
$router->get('/accounts/consultant-payables', [AccountsController::class, 'consultantPayables'], ['auth', 'permission:accounts.view,billing.view']);
$router->get('/accounts/unbilled-work', [AccountsController::class, 'unbilledWork'], ['auth', 'permission:accounts.view,billing.view']);
$router->get('/accounts/reports', [AccountsController::class, 'reports'], ['auth', 'permission:accounts.view,billing.view']);
$router->get('/settings', [SettingsController::class, 'index'], ['auth', 'permission:settings.view']);
$router->get('/settings/company', [SettingsController::class, 'company'], ['auth', 'permission:settings.view']);
$router->post('/settings/company', [SettingsController::class, 'updateCompany'], ['auth', 'permission:settings.view']);
$router->get('/settings/service-types', [SettingsController::class, 'serviceTypes'], ['auth', 'permission:settings.view']);
$router->get('/settings/workflow', [SettingsController::class, 'workflow'], ['auth', 'permission:settings.view']);
$router->post('/settings/workflow', [SettingsController::class, 'updateWorkflow'], ['auth', 'permission:settings.view']);
$router->get('/settings/milestones', [SettingsController::class, 'milestones'], ['auth', 'permission:settings.view']);
$router->get('/settings/reminder-templates', [SettingsController::class, 'reminderTemplates'], ['auth', 'permission:settings.view']);
$router->get('/settings/numbering', [SettingsController::class, 'numbering'], ['auth', 'permission:settings.view']);
$router->post('/settings/numbering', [SettingsController::class, 'updateNumbering'], ['auth', 'permission:settings.view']);
$router->get('/settings/role-defaults', [SettingsController::class, 'roleDefaults'], ['auth', 'permission:settings.view']);
$router->get('/settings/document-categories', [SettingsController::class, 'documentCategories'], ['auth', 'permission:settings.view']);
$router->get('/settings/dsc-categories', [SettingsController::class, 'dscCategories'], ['auth', 'permission:settings.view']);
$router->get('/settings/notifications', [SettingsController::class, 'notifications'], ['auth', 'permission:settings.view']);
$router->post('/settings/notifications', [SettingsController::class, 'updateNotifications'], ['auth', 'permission:settings.view']);
$router->get('/settings/security', [SettingsController::class, 'security'], ['auth', 'permission:settings.view']);
$router->post('/settings/security', [SettingsController::class, 'updateSecurity'], ['auth', 'permission:settings.view']);
$router->get('/settings/maintenance', [SettingsController::class, 'maintenance'], ['auth', 'permission:settings.view']);
$router->post('/settings/maintenance', [SettingsController::class, 'logMaintenance'], ['auth', 'permission:settings.view']);
