<?php

declare(strict_types=1);

use Modules\Auth\AuthController;
use Modules\Billing\BillingController;
use Modules\Clients\ClientController;
use Modules\ClientPortal\ClientPortalController;
use Modules\Consultants\ConsultantController;
use Modules\Dashboard\DashboardController;
use Modules\Documents\DocumentController;
use Modules\Reminders\ReminderController;
use Modules\Reports\ReportController;
use Modules\Search\SearchController;
use Modules\ServiceOrders\ServiceOrderController;
use Modules\Users\UserController;
use Modules\Workflow\WorkflowController;

$router->get('/', [AuthController::class, 'showLanding'], ['guest']);
$router->get('/login', [AuthController::class, 'showLogin'], ['guest']);
$router->post('/login', [AuthController::class, 'login'], ['guest']);
$router->get('/forgot-password', [AuthController::class, 'showForgotPassword'], ['guest']);
$router->post('/forgot-password', [AuthController::class, 'forgotPassword'], ['guest']);
$router->get('/reset-password', [AuthController::class, 'showResetPassword'], ['guest']);
$router->post('/reset-password', [AuthController::class, 'resetPassword'], ['guest']);
$router->get('/register-client', [ClientController::class, 'publicCreate'], ['guest']);
$router->post('/register-client', [ClientController::class, 'publicStore'], ['guest']);
$router->get('/change-password', [AuthController::class, 'showChangePassword'], ['auth']);
$router->post('/change-password', [AuthController::class, 'changePassword'], ['auth']);
$router->post('/logout', [AuthController::class, 'logout'], ['auth']);
$router->get('/dashboard', [DashboardController::class, 'index'], ['auth']);
$router->get('/search', [SearchController::class, 'index'], ['auth', 'permission:search.view']);
$router->get('/search/quick', [SearchController::class, 'quick'], ['auth', 'permission:search.quick,search.view']);
$router->get('/search/advanced', [SearchController::class, 'advanced'], ['auth', 'permission:search.advanced']);
$router->get('/search/history', [SearchController::class, 'history'], ['auth', 'permission:search.history,search.audit']);
$router->get('/documents/show', [DocumentController::class, 'show'], ['auth']);
$router->get('/documents/{id}/download', [DocumentController::class, 'download'], ['auth']);
$router->get('/documents/{id}/preview', [DocumentController::class, 'preview'], ['auth']);
$router->post('/documents/replace', [DocumentController::class, 'replace'], ['auth']);
$router->get('/reports', [ReportController::class, 'index'], ['auth', 'permission:reports.view,reports.financial']);
$router->get('/reports/document-access', [ReportController::class, 'documentAccess'], ['auth', 'permission:documents.report']);
$router->get('/reminders', [ReminderController::class, 'index'], ['auth', 'permission:reminders.view']);
$router->get('/reminders/templates', [ReminderController::class, 'templates'], ['auth', 'permission:reminders.view']);
$router->get('/reminders/templates/form', [ReminderController::class, 'templateForm'], ['auth', 'permission:reminders.create,reminders.edit']);
$router->post('/reminders/templates/save', [ReminderController::class, 'saveTemplate'], ['auth', 'permission:reminders.create,reminders.edit']);
$router->get('/reminders/escalations', [ReminderController::class, 'escalations'], ['auth', 'permission:reminders.view']);
$router->get('/reminders/escalations/form', [ReminderController::class, 'escalationForm'], ['auth', 'permission:reminders.create,reminders.edit']);
$router->post('/reminders/escalations/save', [ReminderController::class, 'saveEscalation'], ['auth', 'permission:reminders.create,reminders.edit']);
$router->get('/reminders/register', [ReminderController::class, 'register'], ['auth', 'permission:reminders.report']);
$router->get('/reminders/pending', [ReminderController::class, 'pending'], ['auth', 'permission:reminders.report']);
$router->get('/reminders/effectiveness', [ReminderController::class, 'effectiveness'], ['auth', 'permission:reminders.report']);
$router->get('/reminders/escalation-report', [ReminderController::class, 'escalationReport'], ['auth', 'permission:reminders.report']);
$router->post('/reminders/run-scheduler', [ReminderController::class, 'runScheduler'], ['auth', 'permission:reminders.send']);
$router->get('/reports/clients', [ReportController::class, 'clients'], ['auth', 'permission:reports.view']);
$router->get('/reports/service-orders', [ReportController::class, 'serviceOrders'], ['auth', 'permission:reports.view']);
$router->get('/reports/pso', [ReportController::class, 'pso'], ['auth', 'permission:reports.view']);
$router->get('/reports/invoices', [ReportController::class, 'invoices'], ['auth', 'permission:reports.financial']);
$router->get('/reports/receipts', [ReportController::class, 'receipts'], ['auth', 'permission:reports.financial']);
$router->get('/reports/outstanding', [ReportController::class, 'outstanding'], ['auth', 'permission:reports.financial']);
$router->get('/reports/gst-summary', [ReportController::class, 'gstSummary'], ['auth', 'permission:reports.view']);
$router->get('/reports/revenue', [ReportController::class, 'revenue'], ['auth', 'permission:reports.financial']);
$router->get('/reports/consultants', [ReportController::class, 'consultants'], ['auth', 'permission:reports.view']);
$router->get('/users', [UserController::class, 'index'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->get('/users/create', [UserController::class, 'create'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->post('/users', [UserController::class, 'store'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->get('/users/show', [UserController::class, 'show'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->get('/users/edit', [UserController::class, 'edit'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->post('/users/update', [UserController::class, 'update'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->get('/users/rights', [UserController::class, 'rights'], ['auth']);
$router->post('/users/rights', [UserController::class, 'saveRights'], ['auth']);
$router->post('/users/archive', [UserController::class, 'archive'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->post('/users/activate', [UserController::class, 'activate'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->post('/users/reset-password', [UserController::class, 'resetPassword'], ['auth', 'permission:users.manage.portal,users.manage.internal']);
$router->get('/clients', [ClientController::class, 'index'], ['auth', 'permission:clients.view']);
$router->get('/clients/create', [ClientController::class, 'create'], ['auth', 'permission:clients.create']);
$router->post('/clients', [ClientController::class, 'store'], ['auth', 'permission:clients.create']);
$router->get('/clients/show', [ClientController::class, 'show'], ['auth', 'permission:clients.view']);
$router->get('/clients/credentials', [ClientController::class, 'credentials'], ['auth', 'permission:clients.view']);
$router->get('/clients/edit', [ClientController::class, 'edit'], ['auth', 'permission:clients.edit']);
$router->post('/clients/credentials', [ClientController::class, 'saveCredentials'], ['auth', 'permission:clients.credentials.manage']);
$router->post('/clients/update', [ClientController::class, 'update'], ['auth', 'permission:clients.edit']);
$router->post('/clients/archive', [ClientController::class, 'archive'], ['auth', 'permission:clients.archive']);
$router->get('/client-portal/pso', [ClientPortalController::class, 'index'], ['auth']);
$router->get('/client-portal/account', [ClientPortalController::class, 'account'], ['auth']);
$router->get('/client-portal/pso/create', [ClientPortalController::class, 'create'], ['auth', 'permission:portal.pso.create']);
$router->post('/client-portal/pso', [ClientPortalController::class, 'store'], ['auth', 'permission:portal.pso.create']);
$router->get('/client-portal/pso/show', [ClientPortalController::class, 'show'], ['auth']);
$router->post('/client-portal/payments', [ClientPortalController::class, 'payInvoice'], ['auth']);
$router->post('/client-portal/pso/recommend', [ClientPortalController::class, 'recommendApproval'], ['auth', 'permission:portal.pso.review']);
$router->post('/client-portal/pso/approve', [ClientPortalController::class, 'approve'], ['auth', 'permission:portal.pso.approve']);
$router->post('/client-portal/pso/reject', [ClientPortalController::class, 'reject'], ['auth', 'permission:portal.pso.reject']);
$router->get('/billing', [BillingController::class, 'index'], ['auth', 'permission:billing.view']);
$router->get('/billing/show', [BillingController::class, 'show'], ['auth', 'permission:billing.view']);
$router->get('/billing/invoice', [BillingController::class, 'invoice'], ['auth']);
$router->get('/billing/receipt', [BillingController::class, 'receipt'], ['auth']);
$router->post('/billing/disbursements', [BillingController::class, 'addDisbursement'], ['auth', 'permission:billing.disbursements.manage']);
$router->post('/billing/invoices', [BillingController::class, 'createInvoice'], ['auth', 'permission:billing.invoices.manage']);
$router->post('/billing/payments', [BillingController::class, 'recordPayment'], ['auth', 'permission:billing.payments.manage']);
$router->get('/consultants', [ConsultantController::class, 'index'], ['auth', 'permission:consultants.view']);
$router->get('/consultants/show', [ConsultantController::class, 'show'], ['auth', 'permission:consultants.view,consultants.bills.review,consultants.payments.record']);
$router->post('/consultants/assign', [ConsultantController::class, 'assign'], ['auth', 'permission:consultants.assign']);
$router->post('/consultants/deliverables', [ConsultantController::class, 'uploadDeliverable'], ['auth', 'permission:consultants.deliverables.upload']);
$router->post('/consultants/deliverables/review', [ConsultantController::class, 'reviewDeliverable'], ['auth', 'permission:consultants.deliverables.review']);
$router->post('/consultants/bills', [ConsultantController::class, 'createBill'], ['auth', 'permission:consultants.bills.create']);
$router->post('/consultants/bills/review', [ConsultantController::class, 'reviewBill'], ['auth', 'permission:consultants.bills.review']);
$router->post('/consultants/payments', [ConsultantController::class, 'recordPayment'], ['auth', 'permission:consultants.payments.record']);
$router->get('/service-orders', [ServiceOrderController::class, 'index'], ['auth', 'permission:service_orders.view']);
$router->get('/service-orders/create', [ServiceOrderController::class, 'create'], ['auth', 'permission:service_orders.create']);
$router->post('/service-orders', [ServiceOrderController::class, 'store'], ['auth', 'permission:service_orders.create']);
$router->get('/service-orders/show', [ServiceOrderController::class, 'show'], ['auth', 'permission:service_orders.view']);
$router->post('/workflow/advance', [WorkflowController::class, 'advance'], ['auth', 'permission:workflow.advance']);
$router->post('/workflow/payment', [WorkflowController::class, 'recordPayment'], ['auth', 'permission:workflow.payment.record']);
$router->post('/workflow/acknowledgement', [WorkflowController::class, 'captureAcknowledgement'], ['auth', 'permission:workflow.acknowledgement.capture']);
$router->post('/workflow/e-verification-done', [WorkflowController::class, 'markEVerificationDone'], ['auth', 'permission:workflow.everification.complete']);
$router->post('/workflow/close-procedural', [WorkflowController::class, 'completeProceduralClosure'], ['auth', 'permission:workflow.close.procedural']);
$router->post('/workflow/close-accounting', [WorkflowController::class, 'completeAccountingClosure'], ['auth', 'permission:workflow.close.accounting']);
$router->post('/workflow/close-final', [WorkflowController::class, 'completeFinalClosure'], ['auth', 'permission:workflow.close.final']);
$router->post('/workflow/follow-up', [WorkflowController::class, 'logFollowUp'], ['auth', 'permission:workflow.followup.log']);
